//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventsTable()
        {
            this.tickets = new HashSet<ticket>();
        }
    
        public string eventDescription { get; set; }
        public string eventCategory { get; set; }
        public System.DateTime eventStartDate { get; set; }
        public System.DateTime eventEndDate { get; set; }
        public System.TimeSpan eventStartTime { get; set; }
        public System.TimeSpan eventEndTime { get; set; }
        public bool registration { get; set; }
        public Nullable<decimal> adultPrice { get; set; }
        public Nullable<decimal> childPrice { get; set; }
        public int eventID { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticket> tickets { get; set; }
    }
}
